apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "pgadmin"
  namespace: "infrastructure"
  labels:
    app.kubernetes.io/name: "pgadmin"
    app.kubernetes.io/managed-by: "local"
    app.kubernetes.io/version: "6.10"
    app.kubernetes.io/component: "postgres"
    app.kubernetes.io/part-of: "infrastructure"
data:
  pgadmin-password: aWxpa2V0dXJ0bGVz