apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "postgres"
  namespace: "infrastructure"
  labels:
    app.kubernetes.io/name: "postgres"
    app.kubernetes.io/managed-by: "local"
    app.kubernetes.io/version: "13.7"
    app.kubernetes.io/component: "postgres"
    app.kubernetes.io/part-of: "infrastructure"
data:
  postgres-password: Y2hAbmdtMw==
  dev-password: aWxpa2V0dXJ0bGVz