apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: "postgres"
    app.kubernetes.io/managed-by: "local"
    onedatascan.com/deployment-stage: "infrastructure"
    app.kubernetes.io/version: "13.7"
    app.kubernetes.io/component: "postgres"
    app.kubernetes.io/part-of: "infrastructure"
data:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
  DEV_USER: "partner"
  DEV_PASSWORD: "dev_pass"
  DEV_DB: "dev_db"
  DEV_SCHEMA: "dev_schema"
  TZ: "US/Eastern"
