kind: ServiceAccount
apiVersion: v1
metadata:
  name: postgres
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: "postgres"
    app.kubernetes.io/instance: "postgres"
    app.kubernetes.io/managed-by: "local"
    onedatascan.com/deployment-stage: "infrastructure"
    app.kubernetes.io/version: "13.7"
    app.kubernetes.io/component: "postgres"
    app.kubernetes.io/part-of: "infrastructure"
