apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-dev
  namespace: cert-manager
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: [your@email.com]
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-dev
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
      - dns01:
          route53:
            accessKeyID: [access key]
            hostedZoneID: [zone id]
            region: [zone (us-east-1)]
            secretAccessKeySecretRef:
              key: secret-access-key
              name: route53-credentials-secret