apiVersion: v1
kind: ConfigMap
metadata:
  name: oracle
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: "oracle"
    app.kubernetes.io/managed-by: "local"
    app.kubernetes.io/version: "19.3.0.0"
    app.kubernetes.io/component: "oracle"
    app.kubernetes.io/part-of: "infrastructure"
data:
  ORACLE_SID: "LOCORADEV01"
  ORACLE_PDB: "DEVPDB"
  ORACLE_PWD: "password"
  ORACLE_CHARACTERSET: "UTF-8"
  