kind: ServiceAccount
apiVersion: v1
metadata:
  name: oracle
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: "oracle"
    app.kubernetes.io/instance: "oracle"
    app.kubernetes.io/managed-by: "local"
    onedatascan.com/deployment-stage: "infrastructure"
    app.kubernetes.io/version: "19.3.0.0"
    app.kubernetes.io/component: "oracle"
    app.kubernetes.io/part-of: "infrastructure"
