kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: oracle
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: "oracle"
    app.kubernetes.io/instance: "oracle"
    app.kubernetes.io/managed-by: "local"
    app.kubernetes.io/version: "19.3.0.0"
    app.kubernetes.io/component: "oracle"
    app.kubernetes.io/part-of: "infrastructure"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "oracle"
subjects:
- kind: ServiceAccount
  name: "oracle"
  namespace: "infrastructure"
